when:
  - event: [push, pull_request]
    branch: main

steps:
  - name: commit message
    image: codeberg.org/adamperkowski/commits:latest
    commands:
      - check-commit-message "$(git log -1 --pretty=%B)"
  - name: formatting
    image: mvdan/shfmt:latest-alpine
    commands:
      - shfmt -d .
  - name: shellcheck
    image: koalaman/shellcheck-alpine
    commands:
      - find . -name "*.sh" -exec shellcheck {} +
